[package]
name = "code-name-dune"
version = "0.1.0"
authors = ["Kumar Ankur"]
edition = "2018"

[dependencies]
amethyst = { version = "0.11.0", features = ["nightly", "metal", "json"] }
serde = "*"
specs-physics = { version = "0.3.0", features = ["amethyst"] }
log = "*"
specs-derive = "*"
